### DISCUSSION TITLE
System Back closes the app - stream chat v1

### DISCUSSION THREAD

**Discussion by ghost** [GetStream/stream-chat-flutter#536] [Q&A] [answered]
@imtoori Thanks for your constant support so far, In stream chat v1 develop.
Using system back buttons instead of the top bar Stream chat back button (up button) on android closes the app instead of going back in the navigation stack. Is there a way to fix this?

**Comment by imtoori** [comment, marked as answer]
hey that should be fixed on latest commit on develop
We saw that bug and fixed it already

**Reply by ghost** [reply]
can you point me to the exact commit/ files modified?
Was it a commit on stream chat sdk or the flutter sample apps repository?
Here's the pubspec.yaml dependency, will running flutter pub get solve the issue?

```
  stream_chat_flutter:
    git:
      url: https://github.com/GetStream/stream-chat-flutter.git
      ref: develop
      path: packages/stream_chat_flutter
```
