### ISSUE TITLE
Mute/Unmute doesn´t work as expected

### ISSUE THREAD

**Issue by EtcGonza** [GetStream/stream-chat-flutter#1053]
### Which packages are you using?

stream_chat, stream_chat_flutter

### On what platforms did you experience the issue?

Android

### What version are you using?

I override my dependencies with this fix
https://github.com/GetStream/stream-chat-flutter/pull/1048

### What happened?

Hi! A few days ago a User report a issue with the mute feature, this is the report https://github.com/GetStream/stream-chat-flutter/issues/1046.

I was waiting for this fix beacuse my app needs this mute feature. Today I override my dependencies with the branch who fix it (https://github.com/GetStream/stream-chat-flutter/pull/1048). This is how I did

```
dependencies:
  stream_chat_flutter:
    git:
      url: https://github.com/GetStream/stream-chat-flutter.git
      path: packages/stream_chat_flutter
      ref: 5f75c6949f37c8ed419bf05b3c62ae5c46e8707e # commit hash

#And in dependency_overrides i put this

dependency_overrides:
  stream_chat:
    git:
      url: https://github.com/GetStream/stream-chat-flutter.git
      path: packages/stream_chat
      ref: 5f75c6949f37c8ed419bf05b3c62ae5c46e8707e # commit hash
```

And the fix work, because now I can login. But I found a new bug. When I mute a user the array of Mute is updated adding the user loggued. The actual behavier is like muting myself.

Also It seems that unmute doesn´t work, because I try to unmute (The first time I sent the id of the user I was trying to mute and second time I send my own id) but the array of Mute doesn´t update. Even if a disconnect and reconnect the getStream chat user.

### Steps to reproduce

```bash
Mute Bug:
1. Open a channel
2. Mute the user with the method `muteUser`
3. Print the array of mutes inside of the user logged.

Unmute Bug:
1. Open a channel of a muted user.
2. Unmute the user with the method `unmuteUser`
3. Print the array of mutes inside of the user logged.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
