### ISSUE TITLE
parentMessage not defined on Thread Page 

### ISSUE THREAD

**Issue by realArafatBen** [GetStream/stream-chat-flutter#1130]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

Android

### What version are you using?

stream_chat_flutter: ^4.1.0

### What happened?

After migrating to the new version 4.1.0. am getting `The name parameter 'parentMessage' isn't defined`

### Steps to reproduce

```bash
1. Go to '...'
2. Click on '...'
3. Scroll down to '...'
...
```

### Supporting info to reproduce

```
class ThreadPage extends StatelessWidget {
  const ThreadPage({
    Key? key,
    this.parent,
  }) : super(key: key);

  final Message? parent;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: StreamThreadHeader(
        parent: parent!,
      ),
      body: Column(
        children: <Widget>[
          Expanded(
            child: StreamMessageListView(
              parentMessage: parent,
            ),
          ),
          StreamMessageInput(
            parentMessage: parent,
          ),
        ],
      ),
    );
  }
}
```

### Flutter doctor output

```shell
[√] Flutter (Channel stable, 2.10.5, on Microsoft Windows [Version 10.0.22000.556], locale en-GB)
    • Flutter version 2.10.5 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (3 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Arafat Benson\AppData\Local\Android\Sdk
    • Platform android-31, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\Arafat Benson\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32421.90
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with
      C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.67.0)
    • VS Code at C:\Users\Arafat Benson\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.40.0

[√] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows       • windows-x64    • Microsoft Windows [Version 10.0.22000.556]
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 101.0.4951.54
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 98.0.1108.56

[√] HTTP Host Availability
    • All required HTTP hosts are available
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xsahil03x** [comment]
@realArafatBen have you tried deleting `pubspec.lock` file and running `flutter pub get` again?
Also, can you share your `pubspec.yaml` ?

**Comment by realArafatBen** [comment]
Yes, just deleted my `pubspec.lock` file but got the same error..  `The name parameter 'parentMessage' isn't defined` 


By the same this my `pubspec.yaml` file  

```
name: grad
description: School management software.

publish_to: 'none' 

https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  badges: ^2.0.1
  collection: ^1.15.0
  connectivity_plus: ^2.2.0
  get: ^4.6.1
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.0.2
  flutter_svg: ^1.0.3
  hexcolor: ^2.0.5
  http: ^0.13.1
  jiffy: ^5.0.0
  shared_preferences: ^2.0.6
  sqflite: ^2.0.0+4
  cached_network_image: ^3.2.0
  flutter_feather_icons: ^2.0.0+1
  table_calendar: ^3.0.3
  timelines: ^0.1.0
  get_storage: ^2.0.3
  php_serializer: ^1.1.0
  image_picker: ^0.8.4+11
  onesignal_flutter: ^3.3.0
  timeago: ^3.2.2
  flutter_slidable: ^1.2.0
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  stream_chat_flutter: ^4.1.0
  firebase_messaging: ^11.2.15
  get_it: ^7.2.0
  firebase_core: ^1.15.0
  flutter_local_notifications: ^9.4.1

  dropdown_button2: ^1.4.0
  json_serializable: ^6.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true


  assets:
    - assets/images/logo/
    - assets/images/icons/
    - assets/images/sample/

  fonts:
    - family: Dongle
      fonts:
        - asset: assets/fonts/Dongle/Dongle-Bold.ttf
        - asset: assets/fonts/Dongle/Dongle-Light.ttf
        - asset: assets/fonts/Dongle/Dongle-Regular.ttf
```
