### ISSUE TITLE
Bump minimum compatible Kotlin version to 1.5.20 via desktop_drop

### ISSUE THREAD

**Issue by CalHoll** [GetStream/stream-chat-flutter#1375]
Just want to ping this issue that's "waiting on customer response" since I'm not the original poster I wasn't sure if it would get overlooked: https://github.com/GetStream/stream-chat-flutter/issues/1372

It's holding up a deployment that would fix crashes in production so any priority it could be given would be appreciated!

**Comment by CalHoll** [comment]
`desktop_drop` has merged a commit that fixes the issue but it's not released as a package yet, here's the workaround:

```
dependency_overrides:
  desktop_drop:
    git:
      url: https://github.com/MixinNetwork/flutter-plugins.git
      path: packages/desktop_drop
      ref: 833cda265f2b2e9fe4105d4c56386c5ccd82464a
```

Looks like `image_gallery_saver` is also a problem...

**Comment by CalHoll** [comment]
Here's the fix for image_gallery_saver - it's from the package maintainer, the repo was updated 2 months ago with the fixes for the latest version of flutter but they haven't updated the package on pub.dev

```
image_gallery_saver:
    git:
      url: https://github.com/hui-z/image_gallery_saver.git
      ref: 6676c04a858761736dc6b166ef14887578c6218f
```
