### ISSUE TITLE
google_map_location_picker is incompatible with stream_chat_flutter.

### ISSUE THREAD

**Issue by moatazfouad** [GetStream/stream-chat-flutter#409]
I can't install google_map_location_picker plugin with stream_chat_flutter plugin at all.
google_map_location_picker requires only intl: 0.17.0 plugin but stream_chat_flutter don't support intl: 0.17.0 version
How can I solve that please?
pubspec.yaml
 **google_map_location_picker: ^4.1.7
  stream_chat_flutter: ^1.5.2**
 
error on console 
_Because no versions of stream_chat_flutter match >1.5.2 <2.0.0 and stream_chat_flutter 1.5.2 depends on jiffy ^3.0.1, stream_chat_flutter ^1.5.2 requires jiffy ^3.0.1.
And because no versions of jiffy match >3.0.1 <4.0.0, stream_chat_flutter ^1.5.2 requires jiffy 3.0.1.
And because jiffy 3.0.1 depends on intl ^0.16.0 and google_map_location_picker >=4.1.7 depends on intl ^0.17.0, stream_chat_flutter ^1.5.2 is incompatible with google_map_location_picker >=4.1.7.
So, because test_paytabs depends on both google_map_location_picker ^4.1.7 and stream_chat_flutter ^1.5.2, version solving failed.

pub get failed (1; So, because test_paytabs depends on both google_map_location_picker ^4.1.7 and stream_chat_flutter ^1.5.2, version solving failed.)_

**Comment by imtoori** [comment]
Hi @moatazfouad you should use an older version of the plugin or just wait for us to finish the nnbd migration that will bump up every dependencies in our packages :)
you can check the status [here](https://github.com/GetStream/stream-chat-flutter/pull/381)

**Comment by moatazfouad** [comment]
@imtoori Thanks for your answer!
but as far as I concerned every version of google_map_location_picker depends on intl:0.17.0 version,
so no version of stream_chat_flutter will be compatible with google_map_location_picker.
Can you tell me which version I should use for both plugins? 
actually I am about to finish a project for a client and I need to know how much average time I will wait?

**Comment by imtoori** [comment]
If I'm not wrong 4.1.6 should work for you while we're finishing the migration

**Comment by moatazfouad** [comment]
The same issue, google_map_location_picker depends on flutter_localization: any so its by default depends on the newest version of intl plugin.
I appreciate your hard work on the package but can you please tell me when you will finish?

**Comment by imtoori** [comment]
I think we'll release on monday
btw, are you using `google_map_location_picker: ^4.1.6` or `google_map_location_picker: 4.1.6`?
The second one is the one I'd try

**Comment by moatazfouad** [comment]
**google_map_location_picker: 4.1.6
  stream_chat_flutter: ^1.5.2**
and I get this error 
### Because every version of google_map_location_picker depends on flutter_localizations any from sdk which depends on intl 0.17.0, every version of google_map_location_picker requires intl 0.17.0.
So, because test_paytabs depends on google_map_location_picker 4.1.6 which depends on intl >=0.15.3 <=0.17.0-nullsafety.2, version solving failed.
pub get failed (1; So, because test_paytabs depends on google_map_location_picker 4.1.6 which depends on intl >=0.15.3 <=0.17.0-nullsafety.2, version solving failed.)
 
if it worked for you let me know your Gradle version in your gradle.build file and gradle.properities

**Comment by moatazfouad** [comment]
@imtoori did it work with you? 🧐

**Comment by imtoori** [comment]
sorry I haven't tried, I thought that should have worked looking at the pubspec, but apparently it doesn't
I'll let you know once we release the null-safety version of the package

**Comment by moatazfouad** [comment]
@imtoori I still have the same error in the latest version of the package 😢

**Comment by imtoori** [comment]
@moatazfouad can you try latest version 2.0.0-nullsafety.0?

**Comment by moatazfouad** [comment]
@imtoori I get this new error
```
Because stream_chat_flutter_core <2.0.0-nullsafety.0 depends on rxdart ^0.25.0 and stream_chat_flutter >=2.0.0-nullsafety.0 depends on rxdart ^0.26.0, stream_chat_flutter_core <2.0.0-nullsafety.0 is incompatible with stream_chat_flutter >=2.0.0-nullsafety.0.
So, because test_paytabs depends on both stream_chat_flutter 2.0.0-nullsafety.0 and stream_chat_flutter_core ^1.5.2, version solving failed.

```

**Comment by imtoori** [comment]
can you try again with version 2.0.0-nullsafety.1
there was an error during publishing the package, sorry

**Comment by moatazfouad** [comment]
@imtoori Thanks for your quick answer!
but actually I still have an error 
this is my pubspec.yaml
```
  cupertino_icons: ^1.0.0
  google_maps_flutter: ^2.0.3
  mvc_pattern: 6.3.0
  global_configuration: ^0.1.2
  http: 0.13.1
  html: ^0.14.0+4
  shared_preferences: ^2.0.5
  flutter_html:
  flutter_svg:
  location: 2.5.4
  url_launcher: 6.0.3
  firebase_messaging:
  cached_network_image: ^3.0.0
  flutter_staggered_grid_view: 0.3.2
  intl_utils: any
  carousel_slider: ^2.3.1
  flutter_widget_from_html_core: ^0.5.1+3
  flutter_webview_plugin: ^0.3.11
  geolocator:
  google_fonts:
  intl: 0.17.0
  flutter_paytabs_bridge: ^2.0.3-beta
  stream_chat_flutter: ^2.0.0-nullsafety.0
  google_map_location_picker:
```
