### ISSUE TITLE
Query Members Error

### ISSUE THREAD

**Issue by rlee1990** [GetStream/stream-chat-flutter#498]
**Describe the bug**
When trying to query members I am getting the below error even though I have added a filter as shown below. This was working before changing my package to the ones below.

```
getMembers() {
    return widget.channel.queryMembers(
        sort: [chat.SortOption('last_message_at')],
        pagination: chat.PaginationParams(limit: 25),
        filter: chat.Filter.and([
          chat.Filter.equal('banned', false),
        ])).then((value) {
      setState(() {
        members.addAll(value.members);
        _isLoading = false;
      });
    });
  }
```

**What package are you using? What version?**
```
stream_chat_flutter: 
    git:
      url: https://github.com/GetStream/stream-chat-flutter.git
      ref: develop
      path: ./packages/stream_chat_flutter
dependency_overrides:
    stream_chat:
      git:
        url: https://github.com/GetStream/stream-chat-flutter.git
        ref: develop
        path: ./packages/stream_chat
    stream_chat_flutter_core:
      git:
        url: https://github.com/GetStream/stream-chat-flutter.git
        ref: develop
        path: ./packages/stream_chat_flutter_core
```

**What platform is it about?**
- [x] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS
- [ ] Linux

`[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: StreamChatNetworkError(code: 4, message: QueryMembers failed with error: "filter_conditions is a required field", statusCode: 400, data: ErrorResponse(code: 4, message: QueryMembers failed with error: "filter_conditions is a required field", statusCode: 400, moreInfo: https://getstream.io/chat/docs/api_errors_response))`
