### ISSUE TITLE
Cannot use 'int' userId in JWT token

### ISSUE THREAD

**Issue by omtodkar** [GetStream/stream-chat-flutter#710]
We were using our database user id in client JWT token. In 2.0.0-nullsafety.4 it was working properly but since we upgraded to 2.2.1 client is failing with following error.

```
type 'int' is not a subtype of type 'String?'
```

Due to type casting on following line.
https://github.com/GetStream/stream-chat-flutter/blob/771ba10999daf9af67fcdb6df0c6972b93f4a8c7/packages/stream_chat/lib/src/core/http/token.dart#L49

Can we have following change?

```dart
final userId = jwtBody.claims.getTyped('user_id');
assert(
  userId != null,
  'Invalid `token`, It should contain `user_id`',
);
return Token._(rawValue: rawValue, userId: userId!.toString(), authType: AuthType.jwt);
```

**Comment by omtodkar** [comment]
For those who are facing same issue. Use following in pubspec.yaml

```yaml
stream_chat_flutter:
    git:
      url: https://github.com/omtodkar/stream-chat-flutter.git
      ref: develop
```

**Comment by omtodkar** [comment]
For those who are facing same issue can use following temporary solution.

```yaml
dependencies:
  stream_chat: ^3.0.0
  stream_chat_flutter: ^3.0.0

dependency_overrides:
  stream_chat:
    git:
      url: https://github.com/omtodkar/stream-chat-flutter.git
      path: packages/stream_chat
      ref: develop
```
