### ISSUE TITLE
Public MessageWidgetState

### ISSUE THREAD

**Issue by Siqlain-Hanif** [GetStream/stream-chat-flutter#970]
### Please select which package this feature is related to

stream_chat_flutter

### Which platforms would this feature impact?

iOS, Android

### Is your feature request related to a problem?

I want my domain url attachements to be built differently in order to do so i will need to override these functions "_buildUrlAttachment" and "_buildTextBubble" of MessageWidgetState. 
MessageWidgetState is currently private and can't be extended to override. 
As MessageWidgets is all what i need for my app just needs a bit of tweaking to meet my needs.

### Describe the solution that you'd like

MessageWidgetState is currently private and can't be extended to override.
I want this state to be public, so i can override certain feature to my needs.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Siqlain-Hanif** [comment]
Using version 3.4.0

**Comment by GroovinChip** [comment]
Hi @Siqlain-Hanif! Thanks for filing this request.

You're in luck! `UrlAttachment` and `TextBubble` are being broken out into their own widgets as of #913! If you want to try this out before the PR lands, you can depend on `stream_chat_flutter` in your `pubspec.yaml` like so:

```yaml
stream_chat_flutter:
  git:
    url: https://github.com/GetStream/stream-chat-flutter.git
    ref: desk_web_dev
    path: packages/stream_chat_flutter
```
Please do try this out and let me know if it meets your needs, and if any adjustments need to be made.

Thanks!
